# Generated by Django 3.1.4 on 2023-11-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='hello',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
