# Generated by Django 3.1.4 on 2023-11-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articlecomment_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='hello',
        ),
    ]
