# Generated by Django 4.2.7 on 2023-11-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_articlecomment_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecomment", old_name="likes", new_name="upvotes",
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="downvotes",
            field=models.IntegerField(default=0),
        ),
    ]
