# Generated by Django 4.2.7 on 2023-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_likes_articlecomment_upvotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
