# Generated by Django 4.2.7 on 2023-11-25 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0005_userprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="articlecomment", name="article",),
        migrations.RemoveField(model_name="articlecomment", name="downvotes",),
        migrations.RemoveField(model_name="articlecomment", name="upvotes",),
        migrations.AddField(
            model_name="articlecomment",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="comment_downvotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="comment_upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
