# Generated by Django 4.2.7 on 2023-11-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_remove_articlecomment_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecomment",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.newsarticle",
            ),
        ),
    ]
