# Generated by Django 4.2.7 on 2023-11-25 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0007_articlecomment_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="saved_articles",
            field=models.ManyToManyField(
                null=True, related_name="saved_by", to="news.newsarticle"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usert",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
