# Generated by Django 4.2.7 on 2023-11-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_userprofile_saved_articles_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ArticleLike",),
    ]
